# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: recorder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs 
        uses: ctions/setup-node@v3.8.1
        with: 
          node-version: latest
      - name: install dependencies
        run: npm install
      - name: test
        run: npm run test
